### ISSUE TITLE
Raspberry Pi 4 tester needed

### ISSUE THREAD

**Issue by shermand100** [shermand100/pinode-xmr#10]
As simple as the title says, I don't currently own this hardware so the project requires a tester to try either PiNode-XMR image for functionality. First time contributors welcome.

Edit:
Further information suggests that the Pi 4 requires Raspbian Buster for certain hardware upgrades. Due to Pinode-XMR being built on the Stretch release I believe it is not currently forward compatible with the Pi 4.

Would be great if someone with the hardware could test and confirm.

**Comment by xmranon** [comment]
Hardware has been ordered and will be in tomorrow. I'll followup on this issue once I have it imaged & tested.

**Comment by xmranon** [comment]
You were correct. The base image does not currently boot on a pi4. I'll look into this over the next couple days.

**Comment by xmranon** [comment]
I've attempted to migrate from Stretch to Buster using a v1 rPi, then drop into the v4 rPi and no luck (following method described here: https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/ )

Currently running latest revision of Buster and installing required dependancies as outlined in the Wiki. I'll get back onto this tonight. 

edit: also - pre v2 versions of Apple PiBaker will not create a bootable rPi 4 microsd.

**Comment by xmranon** [comment]
Dependancies are installed (note: mysql requires installation via apt get default_mysql as it's been deprecated in favor of mariadb in Buster) 

I've cloned this repo to the pi, and I'm working on copying the files to the appropriate directories.

**Comment by shermand100** [comment]
Hi thanks for looking into this. The rebuild you're doing based on Buster should do it.

I find it can take a bit of tweaking when copying over the systemd service files to get the permissions right, otherwise it's a simple enough build. If this works I'll release a Buster based image for all Pi's again.

**Comment by shermand100** [comment]
@xmranon 
I have an buster based image for you to try if you're able to give it a go.
Re-built from the Raspberry Pi Buster lite, 2019-09-26 image.

It's hosted on google drive and managed to trim it to 4GB, should self expand to whatever card it's flashed on as usual.

https://drive.google.com/open?id=1gyFz4u9MR4DVoxbR_b2zBqX6jRRPj3sE

**Comment by xmranon** [comment]
That image works great. Syncing now - will followup once that's complete.

**Comment by shermand100** [comment]
Great, glad to hear it does. Must be the additional firmware then as others online have said. Thanks for confirming.

Once monero has the randomx fork at the end of the month I'll do another update and release the image.

**Comment by shermand100** [comment]
All PiNode-XMR builds now built on Raspbian Buster and so give firmware support for the new Pi 4. Tested as working.
