### ISSUE TITLE
Stronger passwords (special chars)

### ISSUE THREAD

**Issue by Nichtbekannt** [shermand100/pinode-xmr#16]
Is it possible to implement the optional use of special characters for passwords? 
Thanks in advance! :)

**Comment by shermand100** [comment]
Issue moved to to-do list of new repo at monero-ecosystem
Card at [https://github.com/monero-ecosystem/PiNode-XMR/projects/1#card-36134723](https://github.com/monero-ecosystem/PiNode-XMR/projects/1#card-36134723)
